# docker stack deploy -c intranet.yml --prune intranet
version: "3.7"
services:
  dmz:
    image: opentracing/nginx-opentracing
    deploy:
      replicas: 1
      update_config:
        order: start-first
      restart_policy:
        condition: any
        delay: 10s
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik

        - traefik.tcp.routers.intranet.rule=HostSNI(`i.trajano.net`)
        - traefik.tcp.routers.intranet.entryPoints=https
        - traefik.tcp.routers.intranet.tls.certresolver=default
        - traefik.tcp.routers.intranet.tls.passthrough=true
        - traefik.tcp.routers.intranet.tls.domains[0].main=i.trajano.net
        - traefik.tcp.routers.intranet.tls.domains[0].sans=i.trajano.net
        - traefik.tcp.routers.intranet.service=intranet

        - traefik.tcp.services.intranet.loadbalancer.server.port=443

    volumes:
      - /d/p/trajano.net/devops-ca-R2.crt:/ca.pem
      - /d/p/trajano.net/intranet_dmz/i.trajano.net.pem:/cert.pem
      - /d/p/trajano.net/intranet_dmz/key.pem:/key.pem
      - /d/p/trajano.net/intranet_dmz/nginx.conf:/etc/nginx/nginx.conf
      - /d/p/trajano.net/intranet_dmz/zipkin-config.json:/etc/zipkin-config.json
    networks:
      - traefik
      - intranet
      - management
  proxy:
    image: traefik:v2.0.1
    ports:
      - 55555:8080
    command:
      - --global.checknewversion=false
      - --global.sendanonymoususage=false

      - --accesslog
      - --api
      - --api.insecure
      - --ping

      - --entrypoints.http.address=:80

      - --providers.docker.endpoint=tcp://daemon:2375
      - --providers.docker.exposedByDefault=false
      - --providers.docker.swarmMode=true
      - --providers.docker.network=intranet
      - "--providers.docker.constraints=Label(`intranet`, `true`)"
      - '--providers.docker.defaultrule=Host(`i.trajano.net`) && PathPrefix(`/{{ .Name | trimPrefix (index .Labels "com.docker.stack.namespace") | trimPrefix "_" | trimPrefix "-" }}`)'

      - --providers.file.filename=/traefik-conf.toml

      - --tracing.zipkin.httpEndpoint=http://zipkin:9411/api/v2/spans
    healthcheck:
      test: traefik healthcheck --ping
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: any
        delay: 10s
      resources:
        limits:
          memory: 64M
          cpus: "1.0"
        reservations:
          memory: 16M
    volumes:
      - /d/p/trajano.net/traefik.toml:/traefik-conf.toml
    networks:
      - intranet
      - internal
      - management
  daemon:
    image: alpine/socat
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.5'
          memory: 32M
  ping:
    image: alpine/socat
    command: tcp-listen:8080,fork,reuseaddr tcp:proxy:8080
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 32M
      labels:
        - intranet=true
        - traefik.enable=true
        - traefik.http.routers.ping.rule=Path(`/ping`)
        - traefik.http.routers.ping.entryPoints=http
        - traefik.http.routers.ping.middlewares=default
        - traefik.http.routers.ping.service=ping
        - traefik.http.services.ping.loadbalancer.server.port=8080

        - traefik.http.middlewares.default.chain.middlewares=compress-all@file
    networks:
      - intranet
  whoami:
    image: containous/whoami
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 32M
      labels:
        - intranet=true
        - traefik.enable=true
        - traefik.http.routers.whoami.entryPoints=http
        - traefik.http.routers.whoami.middlewares=default,strip-prefix@file
        - traefik.http.services.whoami.loadbalancer.server.port=80
    networks:
      - intranet
networks:
  traefik:
    external: true
  intranet:
    external: true
  management:
    external: true
  internal:
    internal: true
    attachable: false
