# docker stack deploy -c management.yml --prune management
version: "3.7"
services:
  zipkin:
    image: openzipkin/zipkin
    networks:
      - management
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - management
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

networks:
  management:
    name: management
    internal: true
    attachable: true
